compute_engine_instance:
  image_project: freebsd-org-cloud-dev
  image: family/freebsd-12-2
  platform: freebsd
  cpu: 8
  memory: 16G
  disk: 100

# Build the Airyx system core
airyx_task:
  timeout_in: 120m
  environment:
    KEY: ENCRYPTED[f68765a53df76c1b9cd6d870e0054317f9cc517313bf6c56d0b094a1ad01e968a95e6328b37b53db7840d112ff165c46]
    PKG_CONFIG_PATH: /usr/libdata/pkgconfig:/usr/local/libdata/pkgconfig
  script:
    - fetch -o /tmp/base.txz https://dl.cloudsmith.io/public/airyx/core/raw/files/base.txz
    - tar -C / -xf /tmp/base.txz --exclude=./var/empty --exclude=./usr/lib --exclude=./sbin/init --exclude=./lib/libthr.so.3 --exclude=./libcrypt.so.5 --exclude=./lib/libc.so.7 --exclude=./libexec/ld-elf.so.1 --exclude=./usr/bin/crontab --exclude=./usr/bin/su --exclude=./usr/bin/opiepasswd --exclude=./usr/bin/passwd --exclude=./usr/bin/opieinfo --exclude=./usr/bin/login --exclude=./usr/bin/chpass --exclude=./usr/lib/librt.so.1
    - cp -afv mk/*.mk /usr/share/mk
    - cp -fv etc/pkg/*.conf /etc/pkg/ && rm -fv /etc/pkg/FreeBSD.conf
    - fetch -o /tmp/liblz4.pkg https://dl.cloudsmith.io/public/airyx/core/raw/files/liblz4-1.9.3,1.pkg
    - tar -C / -xf /tmp/liblz4.pkg
    - fetch -o /tmp/libarchive.pkg https://dl.cloudsmith.io/public/airyx/core/raw/files/libarchive-3.5.1,1.pkg
    - tar -C / -xf /tmp/libarchive.pkg
    - pkg update
    - pkg install -y cmake jpeg-turbo openjpeg tiff png cairo fontconfig freetype2 libX11 libXext libXfixes libXdamage mesa-libs dbus pkgconf libqtxdg sqlite3 git-tiny qt5-buildtools qt5-qmake qt5-dbus qt5-linguisttools qt5-widgets qt5-x11extras qt5-dbus glib dbus-glib libffi libfm libfm-qt menu-cache gettext-runtime icu kf5-extra-cmake-modules lxqt-build-tools kf5-ki18n kf5-plasma-framework kf5-ktexteditor qt5-testlib gmake autoconf zip bash alsa-lib alsa-plugins
    - fetch -o /tmp/openjdk-17.jdk.txz https://github.com/mszoek/airyx/releases/download/jdk-17.0.1/openjdk-17.0.1.jdk.txz
    - mkdir -p /Library/Java/JavaVirtualMachines
    - tar -C /Library/Java/JavaVirtualMachines -xf /tmp/openjdk-17.jdk.txz
    - make prep airyx
    - rm -f dist/airyx.txz
    - make airyx-package
  only_if: $CIRRUS_BRANCH == 'main'
  airyx_artifacts:
    path: dist/airyx.txz
  package_artifacts:
    path: dist/airyx-*.pkg
